name: CI
on: 
  push:
    branches:
      - master
jobs:
  build:
    name: Make build
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v1
      with:
        node-version: '12.x'
        registry-url: 'https://registry.npmjs.org'
    - run: yarn install
    - run: yarn build
    - name: Add and Commit changes to pr-pages branch
      run: |
        git config --local user.email 'action@github.com'
        git config --local user.name 'GitHub Action'
        git add dist/*
        git commit -m 'Add build'
    - name: Push changes
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        branch: master
